/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5eZxHo5mwvsHRy3bMHe9eQ
// Component: DfO5c0r_8AjP
import * as React from "react";
import {
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 5eZxHo5mwvsHRy3bMHe9eQ/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: DfO5c0r_8AjP/css
import UnionIcon from "./icons/PlasmicIcon__Union"; // plasmic-import: 3slTmvq8R9Gc/icon
import IconInstagramAltIconIcon from "./icons/PlasmicIcon__IconInstagramAltIcon"; // plasmic-import: nP5gJLWyiZXQ/icon
import IconWhatsappIcon from "./icons/PlasmicIcon__IconWhatsapp"; // plasmic-import: YgTnhJlyIUxA/icon
import Group168Icon from "./icons/PlasmicIcon__Group168"; // plasmic-import: 3XQD2Mgu2AHF/icon

createPlasmicElementProxy;

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

const $$ = {};

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"competition"}
            data-plasmic-override={overrides.competition}
            className={classNames(projectcss.all, sty.competition)}
          >
            <div
              data-plasmic-name={"navBarDesign"}
              data-plasmic-override={overrides.navBarDesign}
              className={classNames(projectcss.all, sty.navBarDesign)}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"frame8"}
                data-plasmic-override={overrides.frame8}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame8)}
              >
                <div
                  data-plasmic-name={"mujUnityFestLogo61"}
                  data-plasmic-override={overrides.mujUnityFestLogo61}
                  className={classNames(projectcss.all, sty.mujUnityFestLogo61)}
                />

                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame1"}
                  data-plasmic-override={overrides.frame1}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame1)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame9"}
                    data-plasmic-override={overrides.frame9}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame9)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__m5Jzo
                      )}
                    >
                      {"Home"}
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame10"}
                    data-plasmic-override={overrides.frame10}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame10)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__uy6MW
                      )}
                    >
                      {"Competitions"}
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame13"}
                    data-plasmic-override={overrides.frame13}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame13)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__pXxkp
                      )}
                    >
                      {"Sponsor"}
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame11"}
                    data-plasmic-override={overrides.frame11}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame11)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__sQv2U
                      )}
                    >
                      {"About Us"}
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame12"}
                    data-plasmic-override={overrides.frame12}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame12)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vTpGn
                      )}
                    >
                      {"Contact Us"}
                    </div>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame7"}
                  data-plasmic-override={overrides.frame7}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame7)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"primaryBtn"}
                    data-plasmic-override={overrides.primaryBtn}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.primaryBtn)}
                  >
                    <div
                      data-plasmic-name={"primaryButton"}
                      data-plasmic-override={overrides.primaryButton}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.primaryButton
                      )}
                    >
                      {"Login"}
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"primaryBtn2"}
                    data-plasmic-override={overrides.primaryBtn2}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.primaryBtn2)}
                  >
                    <div
                      data-plasmic-name={"secondaryButton"}
                      data-plasmic-override={overrides.secondaryButton}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.secondaryButton
                      )}
                    >
                      {"Signup"}
                    </div>
                  </Stack__>
                </Stack__>
              </Stack__>
            </div>
            <div
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames(projectcss.all, sty.footer)}
            >
              <UnionIcon
                className={classNames(projectcss.all, sty.svg__mWnFv)}
                role={"img"}
              />

              <div
                data-plasmic-name={"mujUnityFestLogo62"}
                data-plasmic-override={overrides.mujUnityFestLogo62}
                className={classNames(projectcss.all, sty.mujUnityFestLogo62)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__jYDgf
                )}
              >
                {
                  "Uniting Students, Building Connections, Creating Lasting Memories Together"
                }
              </div>
              <div
                data-plasmic-name={"group171"}
                data-plasmic-override={overrides.group171}
                className={classNames(projectcss.all, sty.group171)}
              >
                <div
                  data-plasmic-name={"group169"}
                  data-plasmic-override={overrides.group169}
                  className={classNames(projectcss.all, sty.group169)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__e50E9
                    )}
                  >
                    {"Home"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__iGt6W
                    )}
                  >
                    {"Competitions"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___9VsbO
                    )}
                  >
                    {"Sponsor"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__eojso
                    )}
                  >
                    {"About Us"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ddKx1
                    )}
                  >
                    {"Contact Us"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"group170"}
                  data-plasmic-override={overrides.group170}
                  className={classNames(projectcss.all, sty.group170)}
                >
                  <IconInstagramAltIconIcon
                    className={classNames(projectcss.all, sty.svg__uLwXm)}
                    role={"img"}
                  />

                  <IconWhatsappIcon
                    className={classNames(projectcss.all, sty.svg__oTLu)}
                    role={"img"}
                  />
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"rectangle6"}
              data-plasmic-override={overrides.rectangle6}
              className={classNames(projectcss.all, sty.rectangle6)}
            />

            <Stack__
              as={"div"}
              data-plasmic-name={"frame6939"}
              data-plasmic-override={overrides.frame6939}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame6939)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__zsPvX
                )}
              >
                {"Competitions"}
              </div>
            </Stack__>
            <Group168Icon
              className={classNames(projectcss.all, sty.svg__uwRm2)}
              role={"img"}
            />

            <div
              data-plasmic-name={"rectangle114"}
              data-plasmic-override={overrides.rectangle114}
              className={classNames(projectcss.all, sty.rectangle114)}
            />

            <Stack__
              as={"div"}
              data-plasmic-name={"frame6940"}
              data-plasmic-override={overrides.frame6940}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame6940)}
            >
              <div
                data-plasmic-name={"image"}
                data-plasmic-override={overrides.image}
                className={classNames(projectcss.all, sty.image)}
              />
            </Stack__>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__sivvd
              )}
            >
              {"Treasure Hunt"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__mxHl3
              )}
            >
              {"Uncover hidden treasures in a race against time!"}
            </div>
            <div
              data-plasmic-name={"rectangle115"}
              data-plasmic-override={overrides.rectangle115}
              className={classNames(projectcss.all, sty.rectangle115)}
            />

            <div
              data-plasmic-name={"rectangle116"}
              data-plasmic-override={overrides.rectangle116}
              className={classNames(projectcss.all, sty.rectangle116)}
            />

            <Stack__
              as={"div"}
              data-plasmic-name={"frame6941"}
              data-plasmic-override={overrides.frame6941}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame6941)}
            >
              <div
                data-plasmic-name={"image2"}
                data-plasmic-override={overrides.image2}
                className={classNames(projectcss.all, sty.image2)}
              />
            </Stack__>
            <Stack__
              as={"div"}
              data-plasmic-name={"frame6942"}
              data-plasmic-override={overrides.frame6942}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame6942)}
            >
              <div
                data-plasmic-name={"image3"}
                data-plasmic-override={overrides.image3}
                className={classNames(projectcss.all, sty.image3)}
              />
            </Stack__>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__rnp3D
              )}
            >
              {"Quiz Competiton"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ruv66
              )}
            >
              {"Lame Jokes"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___1Zkex
              )}
            >
              {"Test your knowledge and claim the crown of the trivia king!"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__e0CS8
              )}
            >
              {"Get ready for some cringeworthy laughs!"}
            </div>
            <div
              data-plasmic-name={"rectangle117"}
              data-plasmic-override={overrides.rectangle117}
              className={classNames(projectcss.all, sty.rectangle117)}
            />

            <div
              data-plasmic-name={"rectangle119"}
              data-plasmic-override={overrides.rectangle119}
              className={classNames(projectcss.all, sty.rectangle119)}
            />

            <Stack__
              as={"div"}
              data-plasmic-name={"frame6943"}
              data-plasmic-override={overrides.frame6943}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame6943)}
            >
              <div
                data-plasmic-name={"image4"}
                data-plasmic-override={overrides.image4}
                className={classNames(projectcss.all, sty.image4)}
              />
            </Stack__>
            <Stack__
              as={"div"}
              data-plasmic-name={"frame6945"}
              data-plasmic-override={overrides.frame6945}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame6945)}
            >
              <div
                data-plasmic-name={"image5"}
                data-plasmic-override={overrides.image5}
                className={classNames(projectcss.all, sty.image5)}
              />
            </Stack__>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__kcIlO
              )}
            >
              {"Speed Typing"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__pyjzo
              )}
            >
              {"PUBG"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__vPh7F
              )}
            >
              {"Type your way to victory with lightning speed!"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__qRmFw
              )}
            >
              {"Solve mind-bending puzzles and challenge your brain!"}
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "competition",
    "navBarDesign",
    "frame8",
    "mujUnityFestLogo61",
    "frame1",
    "frame9",
    "frame10",
    "frame13",
    "frame11",
    "frame12",
    "frame7",
    "primaryBtn",
    "primaryButton",
    "primaryBtn2",
    "secondaryButton",
    "footer",
    "mujUnityFestLogo62",
    "group171",
    "group169",
    "group170",
    "rectangle6",
    "frame6939",
    "rectangle114",
    "frame6940",
    "image",
    "rectangle115",
    "rectangle116",
    "frame6941",
    "image2",
    "frame6942",
    "image3",
    "rectangle117",
    "rectangle119",
    "frame6943",
    "image4",
    "frame6945",
    "image5"
  ],

  competition: [
    "competition",
    "navBarDesign",
    "frame8",
    "mujUnityFestLogo61",
    "frame1",
    "frame9",
    "frame10",
    "frame13",
    "frame11",
    "frame12",
    "frame7",
    "primaryBtn",
    "primaryButton",
    "primaryBtn2",
    "secondaryButton",
    "footer",
    "mujUnityFestLogo62",
    "group171",
    "group169",
    "group170",
    "rectangle6",
    "frame6939",
    "rectangle114",
    "frame6940",
    "image",
    "rectangle115",
    "rectangle116",
    "frame6941",
    "image2",
    "frame6942",
    "image3",
    "rectangle117",
    "rectangle119",
    "frame6943",
    "image4",
    "frame6945",
    "image5"
  ],

  navBarDesign: [
    "navBarDesign",
    "frame8",
    "mujUnityFestLogo61",
    "frame1",
    "frame9",
    "frame10",
    "frame13",
    "frame11",
    "frame12",
    "frame7",
    "primaryBtn",
    "primaryButton",
    "primaryBtn2",
    "secondaryButton"
  ],

  frame8: [
    "frame8",
    "mujUnityFestLogo61",
    "frame1",
    "frame9",
    "frame10",
    "frame13",
    "frame11",
    "frame12",
    "frame7",
    "primaryBtn",
    "primaryButton",
    "primaryBtn2",
    "secondaryButton"
  ],

  mujUnityFestLogo61: ["mujUnityFestLogo61"],
  frame1: ["frame1", "frame9", "frame10", "frame13", "frame11", "frame12"],
  frame9: ["frame9"],
  frame10: ["frame10"],
  frame13: ["frame13"],
  frame11: ["frame11"],
  frame12: ["frame12"],
  frame7: [
    "frame7",
    "primaryBtn",
    "primaryButton",
    "primaryBtn2",
    "secondaryButton"
  ],

  primaryBtn: ["primaryBtn", "primaryButton"],
  primaryButton: ["primaryButton"],
  primaryBtn2: ["primaryBtn2", "secondaryButton"],
  secondaryButton: ["secondaryButton"],
  footer: ["footer", "mujUnityFestLogo62", "group171", "group169", "group170"],
  mujUnityFestLogo62: ["mujUnityFestLogo62"],
  group171: ["group171", "group169", "group170"],
  group169: ["group169"],
  group170: ["group170"],
  rectangle6: ["rectangle6"],
  frame6939: ["frame6939"],
  rectangle114: ["rectangle114"],
  frame6940: ["frame6940", "image"],
  image: ["image"],
  rectangle115: ["rectangle115"],
  rectangle116: ["rectangle116"],
  frame6941: ["frame6941", "image2"],
  image2: ["image2"],
  frame6942: ["frame6942", "image3"],
  image3: ["image3"],
  rectangle117: ["rectangle117"],
  rectangle119: ["rectangle119"],
  frame6943: ["frame6943", "image4"],
  image4: ["image4"],
  frame6945: ["frame6945", "image5"],
  image5: ["image5"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    competition: makeNodeComponent("competition"),
    navBarDesign: makeNodeComponent("navBarDesign"),
    frame8: makeNodeComponent("frame8"),
    mujUnityFestLogo61: makeNodeComponent("mujUnityFestLogo61"),
    frame1: makeNodeComponent("frame1"),
    frame9: makeNodeComponent("frame9"),
    frame10: makeNodeComponent("frame10"),
    frame13: makeNodeComponent("frame13"),
    frame11: makeNodeComponent("frame11"),
    frame12: makeNodeComponent("frame12"),
    frame7: makeNodeComponent("frame7"),
    primaryBtn: makeNodeComponent("primaryBtn"),
    primaryButton: makeNodeComponent("primaryButton"),
    primaryBtn2: makeNodeComponent("primaryBtn2"),
    secondaryButton: makeNodeComponent("secondaryButton"),
    footer: makeNodeComponent("footer"),
    mujUnityFestLogo62: makeNodeComponent("mujUnityFestLogo62"),
    group171: makeNodeComponent("group171"),
    group169: makeNodeComponent("group169"),
    group170: makeNodeComponent("group170"),
    rectangle6: makeNodeComponent("rectangle6"),
    frame6939: makeNodeComponent("frame6939"),
    rectangle114: makeNodeComponent("rectangle114"),
    frame6940: makeNodeComponent("frame6940"),
    image: makeNodeComponent("image"),
    rectangle115: makeNodeComponent("rectangle115"),
    rectangle116: makeNodeComponent("rectangle116"),
    frame6941: makeNodeComponent("frame6941"),
    image2: makeNodeComponent("image2"),
    frame6942: makeNodeComponent("frame6942"),
    image3: makeNodeComponent("image3"),
    rectangle117: makeNodeComponent("rectangle117"),
    rectangle119: makeNodeComponent("rectangle119"),
    frame6943: makeNodeComponent("frame6943"),
    image4: makeNodeComponent("image4"),
    frame6945: makeNodeComponent("frame6945"),
    image5: makeNodeComponent("image5"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
